### ISSUE TITLE
set dimensionality as fraction

### ISSUE THREAD

**Issue by lacava** [lacava/fewtwo#33]
allow dimensionality to be set as a fraction of the dimensionality of the data. so user can write 

set_dim('1.5x')

and the maximum dimensionality will be 1.5 times the number of features in the raw dataset. 

this will have to be set within the fit method to work, otherwise the size of X is uknown.

**Comment by tilakhere** [comment]
commit https://github.com/lacava/fewtwo/commit/638b83ef21ad2e0e00d033f0403a50dd05c2c11f

set_dim logging corrections
