### ISSUE TITLE
additional nodes

### ISSUE THREAD

**Issue by lacava** [lacava/fewtwo#51]
implement these nodes: 

 - [x] xor
 - [x] gaussian  = exp(-x^2)
 - [x] 2d-gaussian = exp(-((x-mean(x))^2/(2*var(x)) + (y-mean(y))^2/var(y)))
 - [x] logit = 1/(1+exp(-x))
 - [x] step = 1 if positive, 0 otherwise
 - [x] sign = 1 if positive, 0 if 0, -1 if negative 
 - [x] tanh = hyperbolic tangent [-1, 1]

**Comment by tilakhere** [comment]
commit https://github.com/lacava/fewtwo/commit/fa685b7160584ccda900f52b051fbf6c851dd212
